steps:
- name: node:15
  entrypoint: npm
  args: ['install']
  timeout: 900s
- name: node:15
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/k8s-skaffold/pack'
  id: 'Build'
  entrypoint: 'pack'
  args: ['build',  '--buildpack', 'gcr.io/paketo-buildpacks/nginx', '--builder',  'paketobuildpacks/builder:full', '--publish', 'us.gcr.io/$PROJECT_ID/$REPO_NAME/$_IMAGE:$SHORT_SHA']  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud deploy releases create 'release-$SHORT_SHA'
    --delivery-pipeline=$_PIPELINE_ID
    --region=$_REGION
    --source=./
    --images=frontend=us.gcr.io/$PROJECT_ID/$REPO_NAME/$_IMAGE:$SHORT_SHA
timeout: 1500s
---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: $_PIPELINE_ID
  description: $_PIPELINE_DESC
  serialPipeline:
  stages:
  - targetId: primary
    profiles: []
  - targetId: secondary
    profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: primary
  description: development cluster
  gke: 
    cluster: projects/$PROJECT_ID/locations/$LOCATION/clusters/$_DEV_CLUSTER
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: secondary
  description: prod cluster
  gke: 
    cluster: projects/$PROJECT_ID/locations/$LOCATION/clusters/$_PROD_CLUSTER
---
substitutions:
  
tags:
  - gcp-cloud-build-deploy-gke
  - frontend-app
  
