apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:             
      containers:
      - name: frontend
        image: frontend-app
        ports:
        - containerPort: 3002
        env:
          - name: NODE_ENV
            value: "production"           
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: frontend
  labels:
    id: frontend-svc
spec:
  ports:
  - name: tcp-rule-frontend
    port: 80
    protocol: TCP
    targetPort: 3002
  type: LoadBalancer
  selector:
    app: frontend-svc
