apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  ports:
  - port: 3002
    name: http
  type: LoadBalancer
  selector:
    app: demo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-dpl
spec:
  selector:
    matchLabels:
      app: demo-dpl
  template:
    metadata:
      labels:
        app: demo-dpl
    spec:
      containers:
      - name: cluster-ci
        image: skaffold-buildpacks-node
        ports:
          - containerPort: 3000